package proxy

import "errors"

var (
	ErrPoolCreation                      error = errors.New("catfish/proxy : error creating pool, closing all pools")
	ErrProxyTcpLlistener                 error = errors.New("catfish/proxy : error starting tcp listener")
	ErrReadStartupMsg                    error = errors.New("catfish/proxy : error reading auth stratup msg")
	ErrReadStartupMsgAfterSSLDecline     error = errors.New("catfish/proxy : error reading auth stratup msg after SSL declined")
	ErrStartupMsgUnexpectedFormat        error = errors.New("catfish/proxy : unexpected startup message")
	ErrAuthFailed                        error = errors.New("catfish/proxy : authentication failed")
	ErrUnknownUser                       error = errors.New("catfish/proxy : unknown user")
	ErrDatabaseConnectionNotConfigured   error = errors.New("catfish/proxy : user not configured to connect to this database")
	ErrClearTextAuthChallengeSend        error = errors.New("catfish/proxy : error during sending clear text challenge to user")
	ErrClearTextAuthRead                 error = errors.New("catfish/proxy : error reading response")
	ErrClearTextAuthUnexpectedFormat     error = errors.New("catfish/proxy : cleartext unexpected PasswordMessage format")
	ErrClearTextAuthInvalidPassword      error = errors.New("catfish.proxy : wrong password")
	ErrMD5AuthSaltGen                    error = errors.New("catfish/proxy : md5 salt generation error")
	ErrMD5AuthChallengeSend              error = errors.New("catfish/proxy : md5 send challenge")
	ErrMD5AuthRead                       error = errors.New("catfish/proxy : md5 read response error")
	ErrMD5AuthUnexpectedFormat           error = errors.New("catfish/proxy : md5 unexpected PasswordMessage format")
	ErrMD5AuthInvalidCredentials         error = errors.New("catfish/proxy : md5 wrong credentials for user")
	ErrSCRAMAuthChallengeSend            error = errors.New("catfish/proxy : scram send mechanism list")
	ErrSCRAMAuthRead                     error = errors.New("catfish/proxy : scram auth read error")
	ErrSCRAMAuthUnexpectedInitFormat     error = errors.New("catfish/proxy : unexpected SASLInitResponse")
	ErrSCRAMAuthUnexpectedMethod         error = errors.New("catfish/proxy : client chose unexpected mechanism scram")
	ErrSCRAMAuthNonceGen                 error = errors.New("catfish/proxy : scram nonce generation failed")
	ErrSCRAMAuthSaltGen                  error = errors.New("catfish/proxy : scram salt generation error")
	ErrSCRAMAuthServerFirstSend          error = errors.New("catfish/proxy : scram send server-first")
	ErrSCRAMAuthClientReadFinal          error = errors.New("catfish/proxy : scram read client-final")
	ErrSCRAMAuthUnexpectedResponseFormat error = errors.New("catfish/proxy : scram unexpected SASLResponse")
	ErrSCRAMAuthParseClientFirst         error = errors.New("catfish/proxy : scram parse client-first")
	ErrSCRAMAuthParseClientFinal         error = errors.New("catfish/proxy : scram parse client-final")
	ErrSCRAMAuthDecodeClientProof        error = errors.New("catfish/proxy : scram decode client proof")
	ErrSCRAMAuthWrongPassword            error = errors.New("catfish/proxy : scram wrong password for user")
	ErrSCRAMAuthServerFinalSend          error = errors.New("catfish/proxy : scram send server-final")
	ErrUnknownAuthMethod                 error = errors.New("catfish/proxy : unknown auth method")
	ErrAuthOKSend                        error = errors.New("catfish/proxy : error sending AuthenticationOk msg")
	ErrParameterStatusSend               error = errors.New("catfish/proxy : error sending parameter statuses by server")
	ErrReadyForQuerySend                 error = errors.New("catfish/proxy : error sending ReadyForQuery msg")
	ErrPoolNotFound                      error = errors.New("catfish/proxy : no pool found for user/database pair")
	ErrPoolAcquire                       error = errors.New("catfish/proxy : failed to acquire connection from pool")
	ErrQueryForward                      error = errors.New("catfish/proxy : failed to forward query to postgres")
	ErrPostgresRead                      error = errors.New("catfish/proxy : lost connection to postgres mid-response")
	ErrScramExpectedGS2Header            error = errors.New("catfish/proxy : expected GS2 header 'n,,'")
	ErrScramNoClientNonce                error = errors.New("catfish/proxy : no client nonce in client-first-message")
	ErrScramMalformedClientFinal         error = errors.New("catfish/proxy : malformed client-final-message")
	ErrScramNonceMismatch                error = errors.New("catfish/proxy : nonce mismatch")
	ErrScramNoProof                      error = errors.New("catfish/proxy : no proof in client-final-message")

	ErrCodeAuthFailed string = "28P01"
	ErrCodeTooBusy           = "53300"
	ErrCodeNoPool            = "3D000"
	ErrCodeConnFailed        = "08006"
)
